# Generated by Django 2.2.12 on 2020-10-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('division', models.CharField(max_length=40)),
                ('estadio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('capacidad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=64)),
                ('estado', models.CharField(max_length=64)),
                ('eqlocales', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('pisicion', models.CharField(max_length=20)),
                ('equipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
    ]
